name: Deploy to Server

on:
  push:
    branches:
      - production  # 当推送到 `production` 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /www/congb19-blog-docsify
          git pull origin production
          docker-compose down
          docker-compose up --build -d
